### ISSUE TITLE
No URL return

### ISSUE THREAD

**Issue by ghost** [xaro/SendToPasteBin#15]
Hi xaro, thank you for the plugin. 

However, I got a problem here. I selected lines of code in Sublime Text and then pressed `ctrl + alt + c`. ST told me he is 'sending to pastebin', but did not return me a URL to that paste. I checked my pastebin account, and no paste had been uploaded.

Here is the config file:

    {
      // See http://pastebin.com/api for api key information
      "api_dev_key":  "5f902f*****",
      "api_user_key": "4f068*****",

      // 0 = Public, 1 = Unlisted, 2 = Private
      "paste_privacy": 0,

      // N = Never, 10M = 10 Minutes, 1H = 1 Hour, 1D = 1 Day, 1W = 1 Week, 2W = 2 Weeks, 1M = 1 Month
      "paste_expiration": "N"
    }

Environment Info:

Mac OS X 10.9, Sublime Text 3065

Should I provide anything more?

**Comment by gsivaprabu** [comment]
Hi @ghost,

Use this link create a key

[Creating api_user_key](http://pastebin.com/api/api_user_key.html)

**Comment by xaro** [comment]
Thanks @gsivaprabu for the responses. I haven't had the time to come back to this because of work.
Closing the issue now.
