### ISSUE TITLE
Bad API Request. Invalid Api Key

### ISSUE THREAD

**Issue by studenton** [xaro/SendToPasteBin#16]
I installed the plugin on Sublime Text 3. When using your plugin, I don't get any URL copied to clipboard. When I tried pasting, the text pasted is "Bad API Request. Invalid API key. I guess the API of PasteBin you are using in the plugin has degraded or expired. Please have a look at the issue.

**Comment by gsivaprabu** [comment]
Hi @studenton ,

Use this link create a key

Creating api_user_key this link http://pastebin.com/api/api_user_key.html

**Comment by harpreetsb** [comment]
still same error

**Comment by gsivaprabu** [comment]
@harpreetsb same logic is working for me

**Comment by harpreetsb** [comment]
i tried like 50 times
generated different api_user_key, nothing works same error.
*Bad API request, invalid api_dev_key*

**Comment by ryanpcmcquen** [comment]
@harpreetsb you need the dev key and your user key, they are separate keys.

Generate them here:

https://pastebin.com/api/api_user_key.html
