### ISSUE TITLE
'N' Never setting uploaded to '1D'

### ISSUE THREAD

**Issue by ghost** [xaro/SendToPasteBin#19]
You didn't specify if I was supposed to put the config information in the system settings or the user settings of sublime so I copied and put under user cause I thought that's what you supposed to do with any package control configuration page. Anyway, I had it set to 'N' and it uploaded to be deleted in 24 hours.. Any thoughts?

**Comment by jakubkeller** [comment]
I'm running into the same issue. Setting anything doesn't stick, it always pastes as 1D (24 hours).

**Comment by ryanpcmcquen** [comment]
You have to create a configuration file called: `SendToPasteBin.sublime-settings` wherever the rest of your settings files live. This worked for me.
